name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy-docker-image-service:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: service/Dockerfile
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            davidwah/service:1.0.0

  # deploy-docker-image-proxy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
  #       name: Checkout
  #       uses: actions/checkout@v2

      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - 
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: proxy/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       davidwah/proxy-lb:1.0.0      